name: Deploy Helix Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Helix CLI (v13.4.63)
        run: npm install -g @adobe/helix-cli@13.4.63