name: Deploy Helix Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Helix CLI (v11.3.1)
        run: npm install -g @adobe/helix-cli@11.3.1

      - name: Deploy to Helix
        run: |
          hlx deploy
          hlx publish