name: Deploy Helix Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Helix CLI
        run: npm install -g @adobe/helix-cli

      - name: Deploy
        run: |
          hlx up --publish